server:
  port: 8082  # 指定服务启动在 8082 端口
spring:
  cloud:
    gateway:
      routes:
        - id: auth  # 定义一个路由的ID，唯一标识
          uri: lb://xiaohongshu-auth  # 使用负载均衡（lb://）将请求路由到名为 xiaohongshu-auth 的服务
          predicates:
            - Path=/auth/**  # 定义请求路径的断言条件，匹配 /auth/ 开头的所有路径
          filters:
            - StripPrefix=1  # 定义过滤器，移除路径的第一个前缀（即移除 /auth）
