server:
  port: 8081

spring:
  datasource:
    #  指定数据库驱动类
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # 数据库连接信息
    url: jdbc:p6spy:mysql://127.0.0.1:3306/xiaohongshu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root


logging:
  level:
    com.mirror.xiaohongshu.auth.domain.mapper: debug
